name: Test build

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install
      run: yarn install

    - name: Lint
      run: yarn lint

    - name: Test
      run: yarn test

    - name: Build
      run: yarn build

    - name: Test & publish code coverage
      uses: paambaati/codeclimate-action@v2.7.5
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID}}
      with:
        coverageCommand: yarn test --collectCoverage
        debug: true
