name: Deploy

on:
  push:
    branches:
      - prod
      - test

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install
        run: yarn install

      - name: Setup Git credentials
        run: |
          git config --global user.name '@davidcsally'
          git config --global user.email 'davidcsally@users.noreply.github.com'
          git remote set-url origin https://$GITHUB_ACTOR:$GITHUB_PAT@github.com/davidcsally/davidcsally.github.io
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_PAT }}

      - name: Deploy
        run: |
          yarn deploy
          ${{ secrets.GITHUB_TOKEN }}
