name: Deploy

on:
  push:
    branches:
      - prod
      - test

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: yarn install

      - name: Setup Git credentials
        run: |
          git config --global user.name '@davidcsally'
          git config --global user.email 'davidcsally@users.noreply.github.com'
          git remote set-url origin https://your_personal_access_token>@github.com/davidcsally/davidcsally.github.io.git

      - name: Deploy to GH Pages
        run: yarn run deploy